### ISSUE TITLE
Power plan does not change automatically on boot

### ISSUE THREAD

**Issue by sourhub226** [aredden/electron-G14Control#36]
"Enable auto power switching" feature does not work on logon when the laptop is booted.
The power plan does not change automatically and remains the same as previously applied plan.

To elaborate,
I connected my changer and the power plan was changed to "Efficient performance" (a custom plan) as expected.

![image](https://user-images.githubusercontent.com/58329492/104092068-89cf1c80-52a7-11eb-9e51-009cb7dd8482.png)

After i shutdown the laptop, i disconnected the charger and booted it again.
On logon, the expected behaviour was that the power plan would be changed to Omega Saver automatically.
**However, the plan remained on Efficient performance, thus draining the battery sooner.**

**Comment by aredden** [comment]
Yeah. I'm still wary of making this change. If someone creates a plan that is harmful for their computer, and it gets applied on boot-- resulting in a crash, it would be the applications fault, and be frustrating to fix since you can't boot into windows without g14control crashing the computer. It's not too hard to just open the app (especially with a global shortcut / rog button remapped) and apply the plan, so I don't think it's a very serious issue.
