### ISSUE TITLE
CPU Tuning Revert Back To Default When Start The game

### ISSUE THREAD

**Issue by hrabdullah** [aredden/electron-G14Control#39]
I just made my own presets in CPU Tuning but its turn back to default when I start a game. But its turn on again when I click apply again on G14 Control.

I made this presets to make stability between Power and Thermal output when boost are enable.
My G14 Configuration is R5/GTX1650TI.

Btw overall very good job. Sorry i didnt have credit card so i cant donate you :(
Sorry for my bad english. Thx.

<img width="572" alt="Screenshot 2021-01-11 194536" src="https://user-images.githubusercontent.com/77277723/104185358-722e9a00-5447-11eb-9ea4-af9e072cb2f1.png">

<img width="960" alt="Cyberpunk 2077 (C) 2020 by CD Projekt RED 11_01_2021 19_51_08" src="https://user-images.githubusercontent.com/77277723/104185394-7eb2f280-5447-11eb-9cb9-17da82ca8009.png">

<img width="960" alt="Cyberpunk 2077 (C) 2020 by CD Projekt RED 11_01_2021 19_52_01" src="https://user-images.githubusercontent.com/77277723/104185420-88d4f100-5447-11eb-8bef-bd269054e09f.png">

**Comment by aredden** [comment]
It's possible that the wattage it's showing in the beginning of a game is just the increased wattage average because of the post-boost wattage & the short term fastest boost wattage, so I'm not sure.

**Comment by aredden** [comment]
You should also be aware that if you apply a fan curve, or an armoury crate plan, or a windows plan after setting the boost, it might overwrite the cpu tuning presets. I've also noticed that *sometimes* the boost values don't get applied when you apply a G14Control plan. I also think that you might actually get better thermals and fps if you just disable boost, since high temps like that will pretty severely cause the cpu to throttle hard.
