### ISSUE TITLE
Remapping the ROG button often launches it minimized

### ISSUE THREAD

**Issue by LavaTiger99** [aredden/electron-G14Control#6]
About 20% of the time it will launch the G14control minimized.

**Comment by aredden** [comment]
Yeah, it was tough to get it to work at all, because windows 10 doesn't like to let a process running in the background to be able to gain focus. It works when minimized, because I put in many hours lol. I could spend time on that, but there are a million other things that are probably more important and I'm a single developer doing this for free.

**Comment by aredden** [comment]
I added this feature in version 0.1.33.

**Comment by aredden** [comment]
I mean, I fixed issue where it would launch minimized. You can toggle whether you want it to minimize to tray or taskbar on the settings page.
